# Generated by Django 4.0.4 on 2022-11-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesAptos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nft', models.PositiveIntegerField(default='')),
                ('image', models.ImageField(default='', upload_to='images')),
                ('description', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'ImagesAptos',
                'verbose_name_plural': 'ImagesAptos',
            },
        ),
    ]
